DarkRP.addPhrase("en", "zombie_approaching", "WARNING: Zombies are approaching!")
DarkRP.addPhrase("en", "zombie_leaving", "Zombies are leaving.")
DarkRP.addPhrase("en", "zombie_spawn_not_exist", "Zombie Spawn %s does not exist.")
DarkRP.addPhrase("en", "zombie_spawn_removed", "You have removed this zombie spawn.")
DarkRP.addPhrase("en", "zombie_spawn_added", "You have added a zombie spawn.")
DarkRP.addPhrase("en", "zombie_maxset", "Maximum amount of zombies is now set to %s")
DarkRP.addPhrase("en", "zombie_enabled", "Zombies are now enabled.")
DarkRP.addPhrase("en", "zombie_disabled", "Zombies are now disabled.")
DarkRP.addPhrase("en", "zombie_toggled", "Zombies toggled.")