include("shared.lua")

function ENT:Initialize()
end

function ENT:Draw()
	self:DrawModel()

	if self:Getamount() < 101 then
        local Pos = self:GetPos()
        local Ang = self:GetAngles()
        surface.SetFont("ChatFont")
        local text = DarkRP.formatMoney(self:Getamount())
        local TextWidth = surface.GetTextSize(text)
        cam.Start3D2D(Pos + Ang:Up() * 0.9, Ang, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
        Ang:RotateAroundAxis(Ang:Right(), 180)
        cam.Start3D2D(Pos, Ang, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
    elseif(self:Getamount() < 1001)then
        local Pos = self:GetPos()
        local Ang = self:GetAngles()
        surface.SetFont("ChatFont")
        local text = DarkRP.formatMoney(self:Getamount())
        local TextWidth = surface.GetTextSize(text)
        cam.Start3D2D(Pos + Vector(0, 0, 10), Ang, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
        Ang:RotateAroundAxis(Ang:Right(), 180)
        cam.Start3D2D(Pos + Vector(0, 0, 10), Ang, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
    elseif(self:Getamount() < 5001)then
        local Pos = self:GetPos()
        local Ang = self:GetAngles()
        surface.SetFont("ChatFont")
        local text = DarkRP.formatMoney(self:Getamount())
        local TextWidth = surface.GetTextSize(text)
        local anga = self:GetAngles()
        anga:RotateAroundAxis(anga:Right(), 180)
        anga:RotateAroundAxis(anga:Forward(), 270)
        cam.Start3D2D(Pos + Vector(0, 0, 10), anga, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
        Ang:RotateAroundAxis(Ang:Forward(), 90)
        cam.Start3D2D(Pos + Vector(0, 0, 10), Ang, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
    elseif(self:Getamount() < 10001)then
        local Pos = self:GetPos()
        local Ang = self:GetAngles()
        surface.SetFont("ChatFont")
        local text = DarkRP.formatMoney(self:Getamount())
        local TextWidth = surface.GetTextSize(text)
        local anga = self:GetAngles()
        anga:RotateAroundAxis(anga:Right(), 180)
        anga:RotateAroundAxis(anga:Forward(), 270)
        cam.Start3D2D(Pos + Vector(0, 0, 5), anga, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
        Ang:RotateAroundAxis(Ang:Forward(), 90)
        cam.Start3D2D(Pos + Vector(0, 0, 5), Ang, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
    elseif(self:Getamount() < 20001 )then
        local Pos = self:GetPos()
        local Ang = self:GetAngles()
        surface.SetFont("ChatFont")
        local text = DarkRP.formatMoney(self:Getamount())
        local TextWidth = surface.GetTextSize(text)
        local anga = self:GetAngles()
        anga:RotateAroundAxis(anga:Right(), 180)
        anga:RotateAroundAxis(anga:Forward(), 270)
        cam.Start3D2D(Pos + Vector(0, 0, 12), anga, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
        Ang:RotateAroundAxis(Ang:Forward(), 90)
        cam.Start3D2D(Pos + Vector(0, 0, 12), Ang, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
    elseif(self:Getamount() > 20001) then
        local Pos = self:GetPos()
        local Ang = self:GetAngles()
        surface.SetFont("ChatFont")
        local text = DarkRP.formatMoney(self:Getamount())
        local TextWidth = surface.GetTextSize(text)
        local anga = self:GetAngles()
        anga:RotateAroundAxis(anga:Right(), 180)
        anga:RotateAroundAxis(anga:Forward(), 270)
        cam.Start3D2D(Pos + Vector(0, 0, 25), anga, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
        Ang:RotateAroundAxis(Ang:Forward(), 90)
        cam.Start3D2D(Pos + Vector(0, 0, 25), Ang, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
    /*
    elseif(self:Getamount() > 1000000) then
        local Pos = self:GetPos()
        local Ang = self:GetAngles()
        surface.SetFont("ChatFont")
        local text = DarkRP.formatMoney(self:Getamount())
        local TextWidth = surface.GetTextSize(text)
        local anga = self:GetAngles()
        anga:RotateAroundAxis(anga:Right(), 180)
        anga:RotateAroundAxis(anga:Forward(), 270)
        cam.Start3D2D(Pos + Vector(0, 0, 50), anga, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
        Ang:RotateAroundAxis(Ang:Forward(), 90)
        cam.Start3D2D(Pos + Vector(0, 0, 50), Ang, 0.1)
            draw.WordBox(2, -TextWidth*0.5, -10, text, "ChatFont", Color(140, 0, 0, 100), Color(255,255,255,255))
        cam.End3D2D()
    */
    end
end

function ENT:Think()
end
